config/routes.rb
Rails.application.routes.draw do

  root 'questions#index'

  get '/register', to: 'registrations#new'
  post '/register', to: 'registrations#create'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', :to => 'sessions#destroy'

  resources :questions, only: [:index, :show] do
    resources :answers, only: [:create]
  end

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :user
  belongs_to :question
end

app/models/question.rb
class Question < ActiveRecord::Base
  ANSWER_THRESHOLD = 1

  has_many :answers
  has_many :users, through: :answers

  def threshold_reached?
    answers.count > ANSWER_THRESHOLD
  end

  def majority_agreed?
    total = answers.count
    yes_total = answers.where(response: true).count
    no_total = answers.where(response: false).count

    yes_percentage = yes_total.to_f / total * 100
    no_percentage = no_total.to_f / total * 100

    (yes_percentage > 90) || (no_percentage > 90)
  end

  def resolved?
    threshold_reached? && majority_agreed?
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true

  has_many :answers
  has_many :questions, through: :answers
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def create
    @answer = Answer.create(answer_params)
    redirect_to question_path(@answer.question)
  end

  def answer_params
    params.require(:answer).permit(:response, :question_id, :user_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def current_user
    User.find(session[:logged_in_user])
  end

  def logged_in?
    session[:logged_in_user].present?
  end

  def login_as(user_id)
    session[:logged_in_user] = user_id
    redirect_to '/'
  end

  def log_out
    reset_session
  end

  helper_method :logged_in?, :current_user
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def index
    @questions = Question.all
  end

  def show
    @answer = Answer.find_or_create_by(user: current_user, question: question)
  end

  def answer_response
    if @answer.response
      "You've answered 'Yes'"
    else
      "You've answered 'No'"
    end
  end

  def question
    @question ||= Question.find_by_id(params[:id])
  end

  def yes_responses_count
    question.answers.where(response: true).count
  end

  def no_responses_count
    question.answers.where(response: false).count
  end

  helper_method :answer_response, :question, :yes_responses_count, :no_responses_count
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def new
    user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.save
      login_as(@user.id)
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    redirect_to '/' if logged_in?
  end

  def create
    user = User.find_by(email: params[:email])
    login_as(user.id)
  end

  def destroy
    if logged_in?
      log_out
    end
    redirect_to '/'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ptop</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if logged_in? %>
  <%= link_to 'Log out', logout_path %>
<% else %>
  <%= link_to 'Log in', login_path %>
  <%= link_to 'Register', register_path %>
<% end %>

<%= yield %>

</body>
</html>

app/views/questions/index.html.haml
.ul
  - @questions.each_with_index do |question, index|
    .li= link_to "Question #{index + 1}", question_path(question)

app/views/questions/show.html.haml
= link_to 'Back to all questions', questions_path
.div
  = image_tag( question.image, width: '300')
.div
  = question.description

- if @answer.response.present?
  = answer_response
  .div
    = yes_responses_count
    people answered 'Yes'
  .div
    = no_responses_count
    people answered 'No'
- else
  = form_for @answer, url: question_answers_path(question) do |f|
    = f.radio_button(:response, true)
    = f.label(:response_true, "Yes")
    = f.radio_button(:response, false)
    = f.label(:response_false, "No")
    = f.hidden_field(:user_id, { value: current_user.id })
    = f.hidden_field(:question_id, { value: question.id })
    = f.submit "Submit answer"